AllCops:
  NewCops: enable
  DisplayCopNames: true
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'
Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'
Metrics/AbcSize:
  Exclude:
    - 'bin/bundle'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/**/**'
    - 'config/initializers/simple_form_bootstrap.rb'
Style/Documentation:
  Enabled: false
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'
Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'