development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: db_user
  password: db_user

test:
  adapter: postgresql
  encoding: unicode
  database: flashcards_test
  pool: 5
  username: db_user
  password: db_user

production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false
